#!/bin/bash

# This script creates your profile on the target, sources it in the shell when
# you log in and removes it afterwards. All in one ssh command!

# WARNING, READ THIS BEFORE USING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# This script disregards ALL man-in-the-middle safety checks and should NOT be
# used when such attacks are possible. But using it on your own local network
# that you control is probably fine. Use this on your own risk, I can't be held
# responsible for any issues caused.

if [ $# -le 2 ]; then
  if [[ $1 == *"."* || $1 == *":"* || $1 == *[a-z]* ]]; then
    # Address contains a dot, colon or text, so probably a complete IP address or hostname
    IP=$1
  else
    # Address contains only a number, so probably last part of an IPv4 address
    IP="192.168.0.$1"
  fi
else
  echo "Usage: ssha <IP> [password]"
  echo "Default password is \"pass\" if no password is specified"
  exit
fi

if [ $# -eq 2 ]; then
    pass="$2"
else
    pass="pass"
fi

# Finds the directory that the script is located in
DIR=$( dirname $( readlink -f "$BASH_SOURCE" ) )

# Build complete .profile
profile=`cat $DIR/profile`
if [ -f $DIR/profile_private ]; then
    profile="$profile
             `cat $DIR/profile_private`"
fi

echo "ssh root@$IP"
sshpass -p "$pass" /usr/bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -t root@$IP "echo '$profile' > /tmp/profile ; ENV=/tmp/profile /bin/sh -l ; rm /tmp/profile"
