#!/bin/bash
# $1 = file to export

ECP_PATH="/tmp/ecp"

export_paths=("$@")

if [ ${#export_paths[@]} -gt 0 ]; then
  for arg in "${export_paths[@]}"; do
    file_path=$( realpath "$arg" )
    echo "$file_path" >> $ECP_PATH
    echo "Exported $file_path"
  done
else
  while IFS= read -r path; do
    [ -z "$path" ] && continue
    cp -r "$path" .
    echo "Imported $path"
  done < "$ECP_PATH"
  echo "" > $ECP_PATH
fi
